Trying gradle task to apply hooks so hooks in .git/hooks folder will remain unchnaged

diff --git a/git-hooks/pre-push b/git-hooks/pre-push
--- a/git-hooks/pre-push
+++ b/git-hooks/pre-push
@@ -1,3 +1,13 @@
-#!/bin/sh
+#! /bin/sh
 
-echo "PRE_PUSH from custom hooks path......"
+RED="\033[0;31m"
+RESET="\033[0m"
+
+echo "--- Running Build ---"
+gradle clean build
+if [ "$?" -ne 0 ]; then
+  echo "${RED} ***** BUILD FAILED ***** ${RESET}"
+  exit 1
+fi
+
+exit 0
